version: '2'

services:
  swagger_service:
    image: 'muratovic/swagger-service'
    container_name: swagger_service
    build:
      context: .
    ports:
      - "8082:8082"
      - "7782:7777"
    depends_on:
      - swagger-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://swagger-db:5432/mydb
      - SPRING_DATASOURCE_USERNAME=compose-postgres
      - SPRING_DATASOURCE_PASSWORD=compose-postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

  swagger-db:
    image: 'postgres:13.1-alpine'
    container_name: swagger-db
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=compose-postgres
      - POSTGRES_PASSWORD=compose-postgres
      - POSTGRES_DB=mydb

volumes:
  postgres-data:
